In [1]:
import numpy as np
import pandas as pd
import os
from dotenv import load_dotenv
load_dotenv()
from datetime import datetime
import ast

## Read data from CSV

In [2]:
raw_df = pd.read_csv(f"{os.getenv('FOLDER_PATH_RAW')}{os.getenv('FACEBOOK_FANPAGE_ID')}1.csv")
raw_df.tail()

,post_id,text,post_text,shared_text,original_text,time,timestamp,image,image_lowquality,images,...,w3_fb_url,reactions,reaction_count,with,page_id,sharers,image_id,image_ids,was_live,fetched_time
666,10161430145771803,Round 1 - Fight!\n\nA Street Fighter 6 demo la...,Round 1 - Fight!\n\nA Street Fighter 6 demo la...,NaN,NaN,2023-04-20 22:40:15,1682030415,NaN,https://scontent-sin6-2.xx.fbcdn.net/v/t15.525...,[],...,https://www.facebook.com/playstation/posts/101...,"{'like': 829, 'love': 155, 'haha': 8, 'wow': 8...",1008,NaN,14104316802,<generator object PostExtractor.extract_sharer...,NaN,[],False,2023-11-29 15:03:32.149452
667,10161429315211803,Unleash your inner beast as the Druid in Diabl...,Unleash your inner beast as the Druid in Diabl...,NaN,NaN,2023-04-20 17:35:00,1682012100,NaN,https://scontent-sin6-2.xx.fbcdn.net/v/t15.525...,[],...,https://www.facebook.com/playstation/posts/101...,"{'like': 755, 'love': 120, 'haha': 5, 'wow': 8...",897,NaN,14104316802,<generator object PostExtractor.extract_sharer...,NaN,[],False,2023-11-29 15:03:41.978630
668,10161429575366803,Great news: Firewalk Studios is joining the Pl...,Great news: Firewalk Studios is joining the Pl...,BLOG.PLAYSTATION.COM\nWelcoming Firewalk Studi...,NaN,2023-04-20 17:12:52,1682010772,NaN,https://external-sin6-2.xx.fbcdn.net/emg1/v/t1...,[],...,https://www.facebook.com/playstation/posts/101...,"{'like': 3047, 'love': 554, 'haha': 77, 'wow':...",3728,NaN,14104316802,<generator object PostExtractor.extract_sharer...,NaN,[],False,2023-11-29 15:03:51.941445
669,10161429455771803,Turn the tides in Crash Team Rumble with power...,Turn the tides in Crash Team Rumble with power...,NaN,NaN,2023-04-20 16:00:56,1682006456,NaN,https://scontent-sin6-4.xx.fbcdn.net/v/t15.525...,[],...,https://www.facebook.com/playstation/posts/101...,"{'like': 16039, 'love': 8209, 'haha': 26, 'wow...",40275,NaN,14104316802,<generator object PostExtractor.extract_sharer...,NaN,[],False,2023-11-29 15:04:06.605362
670,257258567130564,The EU Tekken 7 Fight Nights Invitational is l...,The EU Tekken 7 Fight Nights Invitational is l...,NaN,NaN,2023-04-20 15:46:42,1682005602,NaN,https://scontent-sin6-4.xx.fbcdn.net/v/t15.525...,[],...,https://www.facebook.com/playstation/posts/257...,"{'like': 199, 'love': 33, 'haha': 2, 'wow': 4,...",243,"[{'name': 'Tekken 7', 'link': '/gaming/tekken7...",14104316802,<generator object PostExtractor.extract_sharer...,NaN,[],False,2023-11-29 15:04:16.222872

In [3]:
len(raw_df)

671

In [4]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671 entries, 0 to 670
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   post_id                        671 non-null    object
 1   text                           638 non-null    object
 2   post_text                      638 non-null    object
 3   shared_text                    81 non-null     object
 4   original_text                  9 non-null      object
 5   time                           671 non-null    object
 6   timestamp                      671 non-null    object
 7   image                          168 non-null    object
 8   image_lowquality               670 non-null    object
 9   images                         664 non-null    object
 10  images_description             664 non-null    object
 11  images_lowquality              671 non-null    object
 12  images_lowquality_description  671 non-null    object
 13  video                          429 non-null    object
 14  video_duration_seconds         8 non-null      object
 15  video_height                   8 non-null      object
 16  video_id                       429 non-null    object
 17  video_quality                  8 non-null      object
 18  video_size_MB                  8 non-null      object
 19  video_thumbnail                429 non-null    object
 20  video_watches                  8 non-null      object
 21  video_width                    8 non-null      object
 22  likes                          671 non-null    object
 23  comments                       671 non-null    object
 24  shares                         671 non-null    object
 25  post_url                       671 non-null    object
 26  link                           527 non-null    object
 27  links                          671 non-null    object
 28  user_id                        671 non-null    object
 29  username                       671 non-null    object
 30  user_url                       671 non-null    object
 31  is_live                        671 non-null    object
 32  factcheck                      8 non-null      object
 33  shared_post_id                 9 non-null      object
 34  shared_time                    9 non-null      object
 35  shared_user_id                 9 non-null      object
 36  shared_username                9 non-null      object
 37  shared_post_url                9 non-null      object
 38  available                      671 non-null    object
 39  comments_full                  671 non-null    object
 40  reactors                       671 non-null    object
 41  w3_fb_url                      671 non-null    object
 42  reactions                      671 non-null    object
 43  reaction_count                 671 non-null    object
 44  with                           22 non-null     object
 45  page_id                        671 non-null    object
 46  sharers                        671 non-null    object
 47  image_id                       135 non-null    object
 48  image_ids                      671 non-null    object
 49  was_live                       671 non-null    object
 50  fetched_time                   671 non-null    object
dtypes: object(51)
memory usage: 267.5+ KB

In [5]:
raw_df["comments_full"]

0      <generator object PostExtractor.extract_commen...
1      <generator object PostExtractor.extract_commen...
2      <generator object PostExtractor.extract_commen...
3      <generator object PostExtractor.extract_commen...
4      <generator object PostExtractor.extract_commen...
                             ...
666    <generator object PostExtractor.extract_commen...
667    <generator object PostExtractor.extract_commen...
668    <generator object PostExtractor.extract_commen...
669    <generator object PostExtractor.extract_commen...
670    <generator object PostExtractor.extract_commen...
Name: comments_full, Length: 671, dtype: object

## Data preprocessing

In [6]:
data = raw_df.dropna(axis="columns", thresh=100)
data = raw_df.dropna(subset="w3_fb_url")

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671 entries, 0 to 670
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   post_id                        671 non-null    object
 1   text                           638 non-null    object
 2   post_text                      638 non-null    object
 3   shared_text                    81 non-null     object
 4   original_text                  9 non-null      object
 5   time                           671 non-null    object
 6   timestamp                      671 non-null    object
 7   image                          168 non-null    object
 8   image_lowquality               670 non-null    object
 9   images                         664 non-null    object
 10  images_description             664 non-null    object
 11  images_lowquality              671 non-null    object
 12  images_lowquality_description  671 non-null    object
 13  video                          429 non-null    object
 14  video_duration_seconds         8 non-null      object
 15  video_height                   8 non-null      object
 16  video_id                       429 non-null    object
 17  video_quality                  8 non-null      object
 18  video_size_MB                  8 non-null      object
 19  video_thumbnail                429 non-null    object
 20  video_watches                  8 non-null      object
 21  video_width                    8 non-null      object
 22  likes                          671 non-null    object
 23  comments                       671 non-null    object
 24  shares                         671 non-null    object
 25  post_url                       671 non-null    object
 26  link                           527 non-null    object
 27  links                          671 non-null    object
 28  user_id                        671 non-null    object
 29  username                       671 non-null    object
 30  user_url                       671 non-null    object
 31  is_live                        671 non-null    object
 32  factcheck                      8 non-null      object
 33  shared_post_id                 9 non-null      object
 34  shared_time                    9 non-null      object
 35  shared_user_id                 9 non-null      object
 36  shared_username                9 non-null      object
 37  shared_post_url                9 non-null      object
 38  available                      671 non-null    object
 39  comments_full                  671 non-null    object
 40  reactors                       671 non-null    object
 41  w3_fb_url                      671 non-null    object
 42  reactions                      671 non-null    object
 43  reaction_count                 671 non-null    object
 44  with                           22 non-null     object
 45  page_id                        671 non-null    object
 46  sharers                        671 non-null    object
 47  image_id                       135 non-null    object
 48  image_ids                      671 non-null    object
 49  was_live                       671 non-null    object
 50  fetched_time                   671 non-null    object
dtypes: object(51)
memory usage: 267.5+ KB

### Drop columns that is not necessory

In [8]:
data = data.drop_duplicates(subset="post_id")
data = data.drop(columns=["was_live", "fetched_time", 
                           "timestamp", "image", "images", 
                           "timestamp", "image", "image_lowquality",
                          "images","images_description", 
                          "images_lowquality_description",
                          "is_live", "w3_fb_url", "user_id", "username", "user_url",
                          "available", "image_id", "image_ids", "post_url"
                          ])


data.head()

,post_id,text,post_text,shared_text,original_text,time,images_lowquality,video,video_duration_seconds,video_height,...,shared_user_id,shared_username,shared_post_url,comments_full,reactors,reactions,reaction_count,with,page_id,sharers
0,730016209160819,NaN,NaN,NaN,NaN,2023-11-25 09:03:46,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 331, 'love': 80, 'haha': 8, 'wow': 1,...",426,NaN,14104316802,<generator object PostExtractor.extract_sharer...
1,729723005856806,PlayStation Plus Premium members can spend two...,PlayStation Plus Premium members can spend two...,NaN,NaN,2023-11-24 18:34:27,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1672, 'love': 286, 'haha': 184, 'wow'...",2198,NaN,14104316802,<generator object PostExtractor.extract_sharer...
2,728763929286047,Share of the Week dives into the rogues galler...,Share of the Week dives into the rogues galler...,NaN,NaN,2023-11-24 17:01:25,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1301, 'love': 502, 'haha': 7, 'wow': ...",1831,NaN,14104316802,<generator object PostExtractor.extract_sharer...
3,729647439197696,Time to talk turkey.\n\nDig in to Black Friday...,Time to talk turkey.\n\nDig in to Black Friday...,NaN,NaN,2023-11-24 15:59:28,['https://scontent-sin6-1.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 577, 'love': 50, 'haha': 89, 'wow': 1...",724,NaN,14104316802,<generator object PostExtractor.extract_sharer...
4,728960592599714,Which PlayStation Shape are you?\n\nプレイステーション ...,Which PlayStation Shape are you?,プレイステーション ／ PlayStation（Japan）\nNovember 23 at...,PlayStation🎮 × King Gnu👑🐃\n限界突破した #ジャイアントヌー が誕...,2023-11-23 09:10:01,['https://scontent-sin6-2.xx.fbcdn.net/v/t15.5...,https://scontent-sin6-4.xx.fbcdn.net/v/t42.179...,NaN,NaN,...,100064853673762,プレイステーション ／ PlayStation（Japan）,https://facebook.com/story.php?story_fbid=pfbi...,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 232, 'love': 43, 'haha': 8, 'wow': 6,...",293,"[{'name': 'プレイステーション ／ PlayStation（Japan）', 'l...",14104316802,<generator object PostExtractor.extract_sharer...

### Create column "has_video" and drop all video columns

In [9]:
has_vid = []
for vid in data["video"]:
    if vid is not np.nan:
        has_vid.append(True)
    else:
        has_vid.append(False)
data["has_vid"] = pd.DataFrame(has_vid)
data.head()

,post_id,text,post_text,shared_text,original_text,time,images_lowquality,video,video_duration_seconds,video_height,...,shared_username,shared_post_url,comments_full,reactors,reactions,reaction_count,with,page_id,sharers,has_vid
0,730016209160819,NaN,NaN,NaN,NaN,2023-11-25 09:03:46,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 331, 'love': 80, 'haha': 8, 'wow': 1,...",426,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False
1,729723005856806,PlayStation Plus Premium members can spend two...,PlayStation Plus Premium members can spend two...,NaN,NaN,2023-11-24 18:34:27,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1672, 'love': 286, 'haha': 184, 'wow'...",2198,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False
2,728763929286047,Share of the Week dives into the rogues galler...,Share of the Week dives into the rogues galler...,NaN,NaN,2023-11-24 17:01:25,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1301, 'love': 502, 'haha': 7, 'wow': ...",1831,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False
3,729647439197696,Time to talk turkey.\n\nDig in to Black Friday...,Time to talk turkey.\n\nDig in to Black Friday...,NaN,NaN,2023-11-24 15:59:28,['https://scontent-sin6-1.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 577, 'love': 50, 'haha': 89, 'wow': 1...",724,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False
4,728960592599714,Which PlayStation Shape are you?\n\nプレイステーション ...,Which PlayStation Shape are you?,プレイステーション ／ PlayStation（Japan）\nNovember 23 at...,PlayStation🎮 × King Gnu👑🐃\n限界突破した #ジャイアントヌー が誕...,2023-11-23 09:10:01,['https://scontent-sin6-2.xx.fbcdn.net/v/t15.5...,https://scontent-sin6-4.xx.fbcdn.net/v/t42.179...,NaN,NaN,...,プレイステーション ／ PlayStation（Japan）,https://facebook.com/story.php?story_fbid=pfbi...,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 232, 'love': 43, 'haha': 8, 'wow': 6,...",293,"[{'name': 'プレイステーション ／ PlayStation（Japan）', 'l...",14104316802,<generator object PostExtractor.extract_sharer...,True

In [10]:
data = data.drop(columns=["video", "video_id", "video_thumbnail"])

data.head()

,post_id,text,post_text,shared_text,original_text,time,images_lowquality,video_duration_seconds,video_height,video_quality,...,shared_username,shared_post_url,comments_full,reactors,reactions,reaction_count,with,page_id,sharers,has_vid
0,730016209160819,NaN,NaN,NaN,NaN,2023-11-25 09:03:46,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 331, 'love': 80, 'haha': 8, 'wow': 1,...",426,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False
1,729723005856806,PlayStation Plus Premium members can spend two...,PlayStation Plus Premium members can spend two...,NaN,NaN,2023-11-24 18:34:27,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1672, 'love': 286, 'haha': 184, 'wow'...",2198,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False
2,728763929286047,Share of the Week dives into the rogues galler...,Share of the Week dives into the rogues galler...,NaN,NaN,2023-11-24 17:01:25,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1301, 'love': 502, 'haha': 7, 'wow': ...",1831,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False
3,729647439197696,Time to talk turkey.\n\nDig in to Black Friday...,Time to talk turkey.\n\nDig in to Black Friday...,NaN,NaN,2023-11-24 15:59:28,['https://scontent-sin6-1.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 577, 'love': 50, 'haha': 89, 'wow': 1...",724,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False
4,728960592599714,Which PlayStation Shape are you?\n\nプレイステーション ...,Which PlayStation Shape are you?,プレイステーション ／ PlayStation（Japan）\nNovember 23 at...,PlayStation🎮 × King Gnu👑🐃\n限界突破した #ジャイアントヌー が誕...,2023-11-23 09:10:01,['https://scontent-sin6-2.xx.fbcdn.net/v/t15.5...,NaN,NaN,NaN,...,プレイステーション ／ PlayStation（Japan）,https://facebook.com/story.php?story_fbid=pfbi...,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 232, 'love': 43, 'haha': 8, 'wow': 6,...",293,"[{'name': 'プレイステーション ／ PlayStation（Japan）', 'l...",14104316802,<generator object PostExtractor.extract_sharer...,True

### Create column "has_image"

In [11]:
has_imp = []
for image in data["images_lowquality"]:
    if image is not np.nan:
        has_imp.append(True)
    else:
        has_imp.append(False)
data["has_image"] = pd.DataFrame(has_imp)
data.head()

,post_id,text,post_text,shared_text,original_text,time,images_lowquality,video_duration_seconds,video_height,video_quality,...,shared_post_url,comments_full,reactors,reactions,reaction_count,with,page_id,sharers,has_vid,has_image
0,730016209160819,NaN,NaN,NaN,NaN,2023-11-25 09:03:46,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 331, 'love': 80, 'haha': 8, 'wow': 1,...",426,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
1,729723005856806,PlayStation Plus Premium members can spend two...,PlayStation Plus Premium members can spend two...,NaN,NaN,2023-11-24 18:34:27,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1672, 'love': 286, 'haha': 184, 'wow'...",2198,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
2,728763929286047,Share of the Week dives into the rogues galler...,Share of the Week dives into the rogues galler...,NaN,NaN,2023-11-24 17:01:25,['https://scontent-sin6-2.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1301, 'love': 502, 'haha': 7, 'wow': ...",1831,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
3,729647439197696,Time to talk turkey.\n\nDig in to Black Friday...,Time to talk turkey.\n\nDig in to Black Friday...,NaN,NaN,2023-11-24 15:59:28,['https://scontent-sin6-1.xx.fbcdn.net/v/t39.3...,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 577, 'love': 50, 'haha': 89, 'wow': 1...",724,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
4,728960592599714,Which PlayStation Shape are you?\n\nプレイステーション ...,Which PlayStation Shape are you?,プレイステーション ／ PlayStation（Japan）\nNovember 23 at...,PlayStation🎮 × King Gnu👑🐃\n限界突破した #ジャイアントヌー が誕...,2023-11-23 09:10:01,['https://scontent-sin6-2.xx.fbcdn.net/v/t15.5...,NaN,NaN,NaN,...,https://facebook.com/story.php?story_fbid=pfbi...,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 232, 'love': 43, 'haha': 8, 'wow': 6,...",293,"[{'name': 'プレイステーション ／ PlayStation（Japan）', 'l...",14104316802,<generator object PostExtractor.extract_sharer...,True,True

In [12]:
data = data.drop(columns="images_lowquality")
data.reset_index()

,index,post_id,text,post_text,shared_text,original_text,time,video_duration_seconds,video_height,video_quality,...,shared_post_url,comments_full,reactors,reactions,reaction_count,with,page_id,sharers,has_vid,has_image
0,0,730016209160819,NaN,NaN,NaN,NaN,2023-11-25 09:03:46,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 331, 'love': 80, 'haha': 8, 'wow': 1,...",426,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
1,1,729723005856806,PlayStation Plus Premium members can spend two...,PlayStation Plus Premium members can spend two...,NaN,NaN,2023-11-24 18:34:27,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1672, 'love': 286, 'haha': 184, 'wow'...",2198,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
2,2,728763929286047,Share of the Week dives into the rogues galler...,Share of the Week dives into the rogues galler...,NaN,NaN,2023-11-24 17:01:25,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1301, 'love': 502, 'haha': 7, 'wow': ...",1831,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
3,3,729647439197696,Time to talk turkey.\n\nDig in to Black Friday...,Time to talk turkey.\n\nDig in to Black Friday...,NaN,NaN,2023-11-24 15:59:28,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 577, 'love': 50, 'haha': 89, 'wow': 1...",724,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
4,4,728960592599714,Which PlayStation Shape are you?\n\nプレイステーション ...,Which PlayStation Shape are you?,プレイステーション ／ PlayStation（Japan）\nNovember 23 at...,PlayStation🎮 × King Gnu👑🐃\n限界突破した #ジャイアントヌー が誕...,2023-11-23 09:10:01,NaN,NaN,NaN,...,https://facebook.com/story.php?story_fbid=pfbi...,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 232, 'love': 43, 'haha': 8, 'wow': 6,...",293,"[{'name': 'プレイステーション ／ PlayStation（Japan）', 'l...",14104316802,<generator object PostExtractor.extract_sharer...,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,666,10161430145771803,Round 1 - Fight!\n\nA Street Fighter 6 demo la...,Round 1 - Fight!\n\nA Street Fighter 6 demo la...,NaN,NaN,2023-04-20 22:40:15,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 829, 'love': 155, 'haha': 8, 'wow': 8...",1008,NaN,14104316802,<generator object PostExtractor.extract_sharer...,NaN,NaN
606,667,10161429315211803,Unleash your inner beast as the Druid in Diabl...,Unleash your inner beast as the Druid in Diabl...,NaN,NaN,2023-04-20 17:35:00,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 755, 'love': 120, 'haha': 5, 'wow': 8...",897,NaN,14104316802,<generator object PostExtractor.extract_sharer...,NaN,NaN
607,668,10161429575366803,Great news: Firewalk Studios is joining the Pl...,Great news: Firewalk Studios is joining the Pl...,BLOG.PLAYSTATION.COM\nWelcoming Firewalk Studi...,NaN,2023-04-20 17:12:52,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 3047, 'love': 554, 'haha': 77, 'wow':...",3728,NaN,14104316802,<generator object PostExtractor.extract_sharer...,NaN,NaN
608,669,10161429455771803,Turn the tides in Crash Team Rumble with power...,Turn the tides in Crash Team Rumble with power...,NaN,NaN,2023-04-20 16:00:56,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 16039, 'love': 8209, 'haha': 26, 'wow...",40275,NaN,14104316802,<generator object PostExtractor.extract_sharer...,NaN,NaN
609,670,257258567130564,The EU Tekken 7 Fight Nights Invitational is l...,The EU Tekken 7 Fight Nights Invitational is l...,NaN,NaN,2023-04-20 15:46:42,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 199, 'love': 33, 'haha': 2, 'wow': 4,...",243,"[{'name': 'Tekken 7', 'link': '/gaming/tekken7...",14104316802,<generator object PostExtractor.extract_sharer...,NaN,NaN

In [13]:
data.head()

,post_id,text,post_text,shared_text,original_text,time,video_duration_seconds,video_height,video_quality,video_size_MB,...,shared_post_url,comments_full,reactors,reactions,reaction_count,with,page_id,sharers,has_vid,has_image
0,730016209160819,NaN,NaN,NaN,NaN,2023-11-25 09:03:46,NaN,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 331, 'love': 80, 'haha': 8, 'wow': 1,...",426,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
1,729723005856806,PlayStation Plus Premium members can spend two...,PlayStation Plus Premium members can spend two...,NaN,NaN,2023-11-24 18:34:27,NaN,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1672, 'love': 286, 'haha': 184, 'wow'...",2198,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
2,728763929286047,Share of the Week dives into the rogues galler...,Share of the Week dives into the rogues galler...,NaN,NaN,2023-11-24 17:01:25,NaN,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 1301, 'love': 502, 'haha': 7, 'wow': ...",1831,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
3,729647439197696,Time to talk turkey.\n\nDig in to Black Friday...,Time to talk turkey.\n\nDig in to Black Friday...,NaN,NaN,2023-11-24 15:59:28,NaN,NaN,NaN,NaN,...,NaN,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 577, 'love': 50, 'haha': 89, 'wow': 1...",724,NaN,14104316802,<generator object PostExtractor.extract_sharer...,False,True
4,728960592599714,Which PlayStation Shape are you?\n\nプレイステーション ...,Which PlayStation Shape are you?,プレイステーション ／ PlayStation（Japan）\nNovember 23 at...,PlayStation🎮 × King Gnu👑🐃\n限界突破した #ジャイアントヌー が誕...,2023-11-23 09:10:01,NaN,NaN,NaN,NaN,...,https://facebook.com/story.php?story_fbid=pfbi...,<generator object PostExtractor.extract_commen...,<generator object PostExtractor.extract_reacto...,"{'like': 232, 'love': 43, 'haha': 8, 'wow': 6,...",293,"[{'name': 'プレイステーション ／ PlayStation（Japan）', 'l...",14104316802,<generator object PostExtractor.extract_sharer...,True,True

### Make a columns name "post_time" to show the frequency of time page post a post

In [14]:
convert_to_time = []
for time in data["time"]:
    try:
        convert_to_time.append(datetime.strptime(time, '%Y-%m-%d %H:%M:%S'))
    except:
        convert_to_time.append(np.nan)
len(convert_to_time)

data["post_time"] = pd.DataFrame(convert_to_time)
data["post_time"] = pd.to_datetime(data["post_time"]).dt.time

In [15]:
data = data.dropna(axis=0, subset=["post_time"])

## Make type of reaction columns

In [16]:
reaction = data["reactions"].apply(ast.literal_eval).apply(pd.Series)
reaction

       like   love   haha   wow  care  sad  angry
0     331.0   80.0    8.0   1.0   3.0  1.0    2.0
1    1672.0  286.0  184.0  36.0  11.0  2.0    7.0
2    1301.0  502.0    7.0   6.0  14.0  NaN    1.0
3     577.0   50.0   89.0   1.0   3.0  NaN    4.0
4     232.0   43.0    8.0   6.0   3.0  NaN    1.0
..      ...    ...    ...   ...   ...  ...    ...
596   841.0  108.0   14.0   6.0   5.0  NaN    3.0
597   946.0  167.0    8.0   3.0  10.0  NaN    1.0
598  1403.0  290.0  101.0  14.0  18.0  1.0    NaN
599  1208.0  230.0   14.0  13.0   9.0  NaN    1.0
600   552.0   88.0    3.0   8.0   3.0  NaN    NaN

[549 rows x 7 columns]

### Convert NaN value into 0 and float into integer

In [17]:
reaction = reaction.fillna(0).astype(int)
reaction

     like  love  haha  wow  care  sad  angry
0     331    80     8    1     3    1      2
1    1672   286   184   36    11    2      7
2    1301   502     7    6    14    0      1
3     577    50    89    1     3    0      4
4     232    43     8    6     3    0      1
..    ...   ...   ...  ...   ...  ...    ...
596   841   108    14    6     5    0      3
597   946   167     8    3    10    0      1
598  1403   290   101   14    18    1      0
599  1208   230    14   13     9    0      1
600   552    88     3    8     3    0      0

[549 rows x 7 columns]

### Add reaction Dataframe into data

In [18]:
data = pd.concat([data, reaction], axis=1)
data

,post_id,text,post_text,shared_text,original_text,time,video_duration_seconds,video_height,video_quality,video_size_MB,...,has_vid,has_image,post_time,like,love,haha,wow,care,sad,angry
0,730016209160819,NaN,NaN,NaN,NaN,2023-11-25 09:03:46,NaN,NaN,NaN,NaN,...,False,True,09:03:46,331,80,8,1,3,1,2
1,729723005856806,PlayStation Plus Premium members can spend two...,PlayStation Plus Premium members can spend two...,NaN,NaN,2023-11-24 18:34:27,NaN,NaN,NaN,NaN,...,False,True,18:34:27,1672,286,184,36,11,2,7
2,728763929286047,Share of the Week dives into the rogues galler...,Share of the Week dives into the rogues galler...,NaN,NaN,2023-11-24 17:01:25,NaN,NaN,NaN,NaN,...,False,True,17:01:25,1301,502,7,6,14,0,1
3,729647439197696,Time to talk turkey.\n\nDig in to Black Friday...,Time to talk turkey.\n\nDig in to Black Friday...,NaN,NaN,2023-11-24 15:59:28,NaN,NaN,NaN,NaN,...,False,True,15:59:28,577,50,89,1,3,0,4
4,728960592599714,Which PlayStation Shape are you?\n\nプレイステーション ...,Which PlayStation Shape are you?,プレイステーション ／ PlayStation（Japan）\nNovember 23 at...,PlayStation🎮 × King Gnu👑🐃\n限界突破した #ジャイアントヌー が誕...,2023-11-23 09:10:01,NaN,NaN,NaN,NaN,...,True,True,09:10:01,232,43,8,6,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,10161442502256803,Perfect lightsaber parries to repel blaster fi...,Perfect lightsaber parries to repel blaster fi...,NaN,NaN,2023-04-29 15:00:02,NaN,NaN,NaN,NaN,...,True,True,14:15:01,841,108,14,6,5,0,3
597,10161446959161803,Zipping into the weekend.,Zipping into the weekend.,NaN,NaN,2023-04-28 22:00:02,NaN,NaN,NaN,NaN,...,True,True,01:30:00,946,167,8,3,10,0,1
598,10161447467776803,We’re seeing the effects of The Last on Us Par...,We’re seeing the effects of The Last on Us Par...,NaN,NaN,2023-04-28 17:01:35,NaN,NaN,NaN,NaN,...,True,True,00:52:30,1403,290,101,14,18,1,0
599,10161446954061803,"The galaxy is now more dangerous than ever, bu...","The galaxy is now more dangerous than ever, bu...",NaN,NaN,2023-04-28 16:15:01,NaN,NaN,NaN,NaN,...,False,True,20:45:03,1208,230,14,13,9,0,1
600,10161447262151803,Share of the Week highlights Ghostwire: Tokyo:...,Share of the Week highlights Ghostwire: Tokyo:...,NaN,NaN,2023-04-28 16:02:18,NaN,NaN,NaN,NaN,...,True,True,19:00:00,552,88,3,8,3,0,0

## Save clean file

In [19]:
data.to_csv(f"{os.getenv('FOLDER_PATH_CLEAN')}{os.getenv('FACEBOOK_FANPAGE_ID')}.csv", mode="w", index=False)